# Generated by Django 3.2.8 on 2022-02-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='price',
            table='Price',
        ),
    ]
